services:
  backend:
    container_name: backend
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      PROXYAPI_KEY: "${PROXYAPI_KEY}"
      PROXYAPI_BASE_URL: "${PROXYAPI_BASE_URL}"
      QDRANT_API_KEY: "${QDRANT_API_KEY}"
      QDRANT_URL: "${QDRANT_URL}"

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      PROXYAPI_KEY: "${PROXYAPI_KEY}"
      QDRANT_API_KEY: "${QDRANT_API_KEY}"
      BACKEND_URL: "${BACKEND_URL}"
    ports:
      - "8501:8501"
    depends_on:
      - backend

  
